---
title: "My title"
author: 
  - Hannah Yu

thanks: "Code and data are available at: https://github.com/hannahyu07/Non-response-rate."
date: today
date-format: long
format: pdf
output:
  quarto::pdf_document:
    latex_engine: xelatex
number-sections: true
bibliography: references.bib
---

# Introduction

Nonresponse rates underlie significant concerns especially in survey research as high nonresponse rates tend to lead to various biases and affect the validity of the findings. In the "Special Virtual Issue on Nonresponse Rates and Nonresponse Adjustments" of the *Journal of Survey Statistics and Methodology* [@cite1], various aspects and adjustments around nonreponse rates are discussed to enhance the understanding of this critical issue. With the purpose to emphasize the in understanding and addressing nonresponse in survey researches, the editorial highlights the importance of methodological advancements in improving the quality of survey data. Focusing on the aspect of mode effects that was mentioned in the issue, this paper further delves into the impact, types, preventions of this aspect on nonresponse rates.

# Understanding Nonresponse and Its Impact

While conducting surveys and collecting data for research, researchers tend to collect data from sample the population that are able to represent the population instead of attempting the virtually imposible task of collecting data from every single individual of the population. However, while collecting data, the scenario nonresponse often occurs. Nonresponse occurs when sampled individuals or units do not participate or failed to provide some part of the data in a survey.

High nonreponse rates are likely to lead to nonresponse bias, where the characteristics of respondents differ from those of nonrespondents [@cite2]. Nonresponse has the possibility to reduce the effective sample size, and limit the accuracy of survey results. Nonresponse bias is extremely difficult to determine given the lack of data; therefore, in order to ensure the accuracy of survey estimates and the validity of the findings, it is important to try to capture as much data as possible from the respondents [@cite3].

# Mode Effects

According to HESA, "A mode effect is a systematic difference that is attributable to the mode of data collection. [@cite4]" And mode effects on nonresponse rates refers to the variation in response rates observed across different modes of data collection in survey research. Different survey modes, such as face-to-face interviews, telephone interviews, mail surveys, and online questionnaire may induce different levels of partipations from respondents.

## Factors Influencing Mode Effects

## Types of Mode Effects

annonymous questioanri

## Mitigating Mode Effects

# Conclusion

# Reference
